parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: gmail
    mailer_host: 127.0.0.1
    mailer_user: XXX@gmail.com
    mailer_password: XXX
    locale: en
    secret: 1ef3cf3fdd3881ef3d2ad27cc6c573b10
    database_path: null
