<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function getBirthdayUsers()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select(array('u', 'g'))
            ->from('AppBundle\Entity\Users', 'u')
            ->leftJoin('u.gender', 'g')
            ->where('u.birth = :birth')
            ->setParameter('birth', new \DateTime(date('Y-m-d')))
            ->getQuery()
            ->getResult();
    }

}
